"use client";

import { useCallback, useEffect, useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";

import { getBlogJob } from "@/lib/api";
import type { BlogJobOut } from "@/lib/types";

export default function BlogPreviewPage() {
  const params = useParams();
  const brandId = params.id as string;
  const jobId = params.jobId as string;

  const [job, setJob] = useState<BlogJobOut | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      setJob(await getBlogJob(brandId, jobId));
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed to load article");
    } finally {
      setLoading(false);
    }
  }, [brandId, jobId]);

  useEffect(() => { load(); }, [load]);

  const draft = job?.draft ?? null;

  return (
    <div className="stack stack-lg">
      <nav className="breadcrumb">
        <Link href="/brands">Brands</Link>
        <span className="breadcrumb-sep">/</span>
        <Link href={`/brands/${brandId}`}>Brand</Link>
        <span className="breadcrumb-sep">/</span>
        <Link href={`/brands/${brandId}/review`}>Review &amp; Publish</Link>
        <span className="breadcrumb-sep">/</span>
        <span style={{ color: "var(--text)", fontWeight: 500 }}>Preview</span>
      </nav>

      {error && (
        <div className="alert alert-warning">
          <span>⚠</span>
          <span>{error} — <button onClick={load} style={{ background: "none", border: "none", color: "var(--accent)", cursor: "pointer", padding: 0 }}>Retry</button></span>
        </div>
      )}

      {loading ? (
        <div className="card" style={{ padding: 24 }}>Loading article…</div>
      ) : !job ? null : !draft ? (
        <div className="card" style={{ padding: 24, textAlign: "center", color: "var(--text-muted)" }}>
          No draft yet for <strong>{job.keyword}</strong>. Status: <strong>{job.status}</strong>.
          {job.error_message && <p className="meta" style={{ marginTop: 8 }}>{job.error_message}</p>}
          <p className="meta" style={{ marginTop: 8 }}>The article appears here once generation finishes.</p>
        </div>
      ) : (
        <article className="card" style={{ padding: "28px 32px" }}>
          <h1 style={{ fontSize: "1.75rem", fontWeight: 700, lineHeight: 1.2 }}>{draft.title}</h1>
          {draft.meta_description && (
            <p className="meta" style={{ marginTop: 8, fontSize: "0.95rem" }}>{draft.meta_description}</p>
          )}
          <div style={{ display: "flex", gap: 16, flexWrap: "wrap", margin: "14px 0 4px", fontSize: "0.8125rem", color: "var(--text-muted)" }}>
            <span>🔑 {job.keyword}</span>
            <span>📝 {draft.word_count} words</span>
            <span>📈 SEO {draft.seo_score}</span>
            <span>🏷 {job.status}</span>
          </div>

          {draft.featured_image_url && (
            // eslint-disable-next-line @next/next/no-img-element
            <img
              src={draft.featured_image_url}
              alt=""
              style={{ width: "100%", maxHeight: 360, objectFit: "cover", borderRadius: 10, margin: "16px 0" }}
            />
          )}

          {/* Article body is HTML generated by our own backend pipeline. */}
          <div
            className="article-body"
            style={{ marginTop: 18, lineHeight: 1.7 }}
            dangerouslySetInnerHTML={{ __html: draft.html_content }}
          />

          <div style={{ marginTop: 24, paddingTop: 16, borderTop: "1px solid var(--border)" }}>
            <Link href={`/brands/${brandId}/review`} className="pill-link" style={{ fontSize: "0.8125rem", height: 34 }}>
              ← Back to review queue to approve or reject
            </Link>
          </div>
        </article>
      )}
    </div>
  );
}
